apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: locked-vscode-redhat-only
spec:
  started: true
  template:
    components:
      - name: vscode
        container:
          image: quay.io/devfile/universal-developer-image:latest
          memoryLimit: 512Mi
          cpuLimit: 250m
          mountSources: false
          env:
            # Strict RedHat extension control
            - name: EXTENSIONS_GALLERY
              value: '{
                "serviceUrl": "https://pwb.jioma.jio.com/openvsx",
                "itemUrl": "",
                "resourceUrlTemplate": "",
                "allowedExtensions": ["redhat.*"]
              }'
            - name: CHE_CODE_EXTENSIONS_ALLOWED_EXTENSIONS
              value: "redhat.*"
            
            # Security lockdown
            - name: CHE_CODE__EXTENSIONS_GALLERY__ENABLED
              value: "false"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"  # Bypass SSL for private registry

          # Ephemeral extension storage
          volumeMounts:
            - name: redhat-extensions
              path: /home/user/.vscode/extensions

    # Storage configuration
    volumes:
      - name: redhat-extensions
        ephemeral: true

    # Workspace attributes
    attributes:
      editor: che-incubator/che-code/latest
      workspace-storage-type: ephemeral
      plugins:
        - editor: che-incubator/che-code/latest
          cpuRequest: 100m
          memoryRequest: 256Mi