apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: locked-vscode-redhat-only-new
spec:
  started: true
  template:
    attributes:
      pod-overrides:
        spec:
          imagePullSecrets:
            - name: jioma-acr-app-containerization-api   # matches the secret you created
    components:
      - name: vscode
        container:
          image: jioazurenonprodpnejiomaregistry.azurecr.io/custom-ide/universal8:1.0
          env:
            - name: CHE_PLUGIN_REGISTRY_URL
              value: "https://pwb.jioma.jio.com/openvsx"
            - name: EXTENSIONS_GALLERY
              value: '{
                "serviceUrl": "https://pwb.jioma.jio.com/openvsx",
                "itemUrl": "https://pwb.jioma.jio.com/openvsx/api/item",
                "resourceUrlTemplate": "https://pwb.jioma.jio.com/openvsx/files/{publisher}/{name}/{version}/{path}",
                "allowedExtensions": ["redhat.*"]
              }'
            - name: CHE_CODE__EXTENSIONS_GALLERY__ENABLED
              value: "false"
            - name: VSCODE_GALLERY_SERVICE_URL
              value: ""
            - name: CHE_CODE_EXTENSIONS_ALLOWED_EXTENSIONS
              value: "redhat.*"
            - name: CHE_PLUGIN_REGISTRY_PRELOADED_EXTENSIONS
              value: "redhat.vscode-redhat-account@0.2.0"
