apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: locked-vscode-redhat-only
spec:
  started: true
  template:
    components:
      - name: vscode
        container:
          image: quay.io/devfile/universal-developer-image:latest
          env:
            # ==== STRICT EXTENSION CONTROL ====
            # (1) Disable all external extensions
            - name: CHE_CODE__EXTENSIONS_GALLERY__ENABLED
              value: "false"
            # (2) Only allow pre-defined RedHat extensions
            - name: CHE_PLUGIN_REGISTRY_PRELOADED_EXTENSIONS
              value: "redhat.vscode-redhat-account@0.2.0"  # << ONLY THIS EXTENSION
            # (3) Block other sources
            - name: VSCODE_EXTENSIONS_DOWNLOAD_URL
              value: ""  # Disable direct downloads
            # (4) SSL bypass (if needed)
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

          volumeMounts:
            - name: redhat-extensions
              path: /home/user/.vscode/extensions

    volumes:
      - name: redhat-extensions
        ephemeral: true

    attributes:
      editor: che-incubator/che-code/latest
      workspace-storage-type: ephemeral